### ISSUE TITLE
Bubble sort implementation and documentation

### ISSUE THREAD

**Issue by Sjsingh101** [Sjsingh101/Basic-JAVA-Programs#1]
Try to write code neatly and documentation in Markdown

**Comment by siddharthnarula1234** [comment]
# Bubble sort is based on the idea of repeatedly comparing pairs of adjacent elements and then swapping their positions if they exist in the wrong order.
![2682167](https://user-images.githubusercontent.com/31994579/66497695-7a788680-eada-11e9-922e-5c063ca85fe2.png)
In step 1,  is compared with . Since ,  is moved ahead of . Since all the other elements are of a lesser value than ,  is moved to the end of the array.

Now the array is .

In step 2,  is compared with . Since  and both  and  are in ascending order, these elements are not swapped. However, when  is compared with ,  and these elements are in descending order. Therefore,  and  are swapped.

Now the array is .

In step 3, the element  is compared with . Since  and the elements are in descending order,  and  are swapped.

The sorted array is .

Complexity:
The complexity of bubble sort is O(n^2)  in both worst and average cases, because the entire array needs to be iterated for every element.

To check here is the code:-
#include<iostream>
#include<conio.h>
#include<dos.h>
#include<time.h>
#include<stdlib.h>
#include<windows.h>
using namespace std;
void swap(int *xp, int *yp)
{
    int temp = *xp;
    *xp = *yp;
    *yp = temp;
}
int shellSort(int arr[], int n)
{
    for (int gap = n/2; gap > 0; gap /= 2)
    {
        for (int i = gap; i < n; i += 1)
        {
            int temp = arr[i];
            int j;
            for (j = i; j >= gap && arr[j - gap] > temp; j -= gap)
                arr[j] = arr[j - gap];
            arr[j] = temp;
        }
    }
    return 0;
}
void printArray(int arr[], int size)
{
    int i;
    for (i = 0; i < size; i++)
	cout << arr[i] << " ";
    cout << endl;
}
int main()
{
clock_t start,end;
    int arr[100],n=10;
    for(int i=0;i<n;i++)
    {
       arr[i] = (rand()%100)+1;
	cout << arr[i] << endl;
    }
    //int n = sizeof(arr)/sizeof(arr[0]);
    start=clock();
    shellSort(arr, 10);
    end=clock();
    cout<<"Sorted array: \n";
    printArray(arr, 10);
    float t=(end-start)/CLK_TCK;
    cout<<"\n Time Taken is"<<t;
    return 0;
}

**Comment by imrishabh18** [comment]
I am doing it.

**Comment by ektagarg** [comment]
hi @Sjsingh101 It needs to be in JAVA only? or can it be in any other language?
If yes, then I would like to take this up.
Thanks :)

**Comment by Zircoz** [comment]
> 
> 
> Try to write code neatly and documentation in Markdown

@Sjsingh101 I would like to take this up in Java as @ektagarg already wants it in other language. May I do it?

**Comment by Sjsingh101** [comment]
@Zircoz yes you can take that but as @vishal1003 has already sent PR then this issue is fixed i will open new issues soon
